### ISSUE TITLE
Error with installation

### ISSUE THREAD

**Issue by janetteng123** [Nicholaswogan/photochem#32]
Hello,

I'm following the instructions to install photochem, but I ran into an error when I tried to run part of the code:
python -m pip install --no-deps --no-build-isolation

Here's the error shown: 
ERROR: You must give at least one requirement to install (see "pip help install")

What can I do to fix this issue? Thanks!

**Comment by Nicholaswogan** [comment]
Hi Janet,

You forgot a "." in your command. Run this command instead

```sh
python -m pip install --no-deps --no-build-isolation . -v
```

**Comment by janetteng123** [comment]
Thank you! There's another error that appeared. I have copied the error in the attached text file.
[Error.txt.txt](https://github.com/Nicholaswogan/photochem/files/12060114/Error.txt.txt)

**Comment by Nicholaswogan** [comment]
do the following commands then try to re-install

```
conda install -c conda-forge cmake ninja
```

**Comment by janetteng123** [comment]
I was able to run the commands you sent: `conda install -c conda-forge cmake ninja`, then this `python -m pip install --no-deps --no-build-isolation . -v` without any errors. Is there any way I can check if I installed it correctly?

I was trying to test whether or not I installed photochem by following the the Tutorial.ipynb in the examples directory. I copied the first few lines that started with import, but I also got an error (attached below). I'm not sure how to fix it
[issue.txt.txt](https://github.com/Nicholaswogan/photochem/files/12060184/issue.txt.txt)

**Comment by Nicholaswogan** [comment]
You are trying to run photochem from the root directory of the Github repo. This will not work because Python will search the `photochem` folder for the compiled c-extensions. But they are not there, because you installed photochem.

Anyway, the solution is to run photochem from any directory that does not contain a subdirectory named "photochem"

**Comment by janetteng123** [comment]
Got it. I'm sorry but I just want to double check again, because I went into a separate directory that does not contain a subdirectory named "photochem", but it seems like I'm getting a similar but slightly different error. Thank you so much for helping me

[error_terminal.txt](https://github.com/Nicholaswogan/photochem/files/12062395/error_terminal.txt)

**Comment by Nicholaswogan** [comment]
That error is saying that you do not have photochem installed in your current active conda environment
